name: Subdomain Takeover Detection

on:
  schedule:
    - cron: '*/30 * * * *' # Run every 30 minutes

jobs:
  subdomain_takeover:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15'

    # Install Windows-compatible versions of tools
    - name: Install subfinder
      run: go get -u -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder

    - name: Install amass
      run: go get -u -v github.com/OWASP/Amass/v3/...

    - name: Install assetfinder
      run: go get -u -v github.com/tomnomnom/assetfinder

    - name: Install subjack
      run: go get -u -v github.com/haccer/subjack

    - name: Install subzy
      run: go get -u -v github.com/lukasikic/subzy

    - name: Read domains from file
      id: read_domains
      run: |
        Get-Content domains.txt

    # Add steps to run commands specific to Windows
    - name: Run Subdomain Enumeration and Takeover Check
      run: |
        $DOMAINS = Get-Content domains.txt
        foreach ($domain in $DOMAINS) {
          Write-Output "Processing $domain"
          subfinder -d $domain -o ${domain}_subdomains.txt
          amass enum -passive -d $domain -o ${domain}_amass.txt
          assetfinder --subs-only $domain | Out-File -FilePath "${domain}_assetfinder.txt" -Append
          # Add other commands as needed
        }

    # Add steps for combining results and sending email
    - name: Combine Results
      run: |
        Get-Content *_results_subjack.txt, *_results_subzy.txt | Set-Content combined_results.txt

    - name: Send Notification Email
      env:
        SMTP_SERVER: smtp.gmail.com
        SMTP_PORT: 587
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        EMAIL_TO: thedevtask@gmail.com
      run: |
        $takeover_detected = (Get-Content combined_results.txt | Measure-Object -Line).Lines
        if ($takeover_detected -gt 0) {
          Send-MailMessage -SmtpServer $SMTP_SERVER -Port $SMTP_PORT -UseSsl -From $SMTP_USER -To $EMAIL_TO -Subject "Subdomain Takeover Detected" -Body "Subdomain takeover detected."
        }
